// react/src/pages/effects/cheat-code.tsx
import { CheatCode } from "@/components/draft/effects/CheatCode"
import { DemoPage } from "@/demo/DemoPage"

export default function CheatCodePage() {
  return (
    <CheatCode onUnlock={() => console.log("unlocked! 🎮")}>
      <DemoPage hint="↑ ↑ ↓ ↓ ← → ← → B A と入力してみてください。" />
    </CheatCode>
  )
}

// nuxt/src/pages/effects/cheat-code.vue
<script setup lang="ts">
import CheatCode from "@/components/draft/effects/CheatCode.vue"
import DemoPage from "@/demo/DemoPage.vue"

const on = () => console.log("unlocked! 🎮")
</script>

<template>
  <CheatCode @unlock="on">
    <DemoPage hint="↑ ↑ ↓ ↓ ← → ← → B A と入力してみてください。" />
  </CheatCode>
</template>
