// react/src/demo/usage/effects/shatter.tsx
import type { ReactNode } from "react"
import { ShatterGlass } from "@/components/draft/effects/ShatterGlass"

// クリックした所からガラスのように割る。破片はドラッグでき、「元に戻す」で直る。
export function Fragile({ children }: { children: ReactNode }) {
  return (
    <ShatterGlass spokes={16} rings={4} jitter={0.5} onShatter={() => console.log("💥")}>
      {children}
    </ShatterGlass>
  )
}

// nuxt/src/pages/effects/shatter.vue
<script setup lang="ts">
import ShatterGlass from "@/components/draft/effects/ShatterGlass.vue"
import DemoPage from "@/demo/DemoPage.vue"

const on = () => console.log("smash! 💥")
</script>

<template>
  <ShatterGlass @shatter="on">
    <DemoPage hint="どこかをクリックすると、その場所からガラスのように割れます。" />
  </ShatterGlass>
</template>
