// react/src/demo/usage/effects/cheat-code.tsx
import type { ReactNode } from "react"
import { CheatCode } from "@/components/draft/effects/CheatCode"

// ↑↑↓↓←→←→BA (コナミコマンド) を入力すると紙吹雪と秘密のバナーを出す。
export function EasterEgg({ children }: { children: ReactNode }) {
  return (
    <CheatCode
      code={["ArrowUp", "ArrowUp", "ArrowDown", "ArrowDown", "b", "a"]} // 省略時はコナミコマンド
      secret={<strong>🎮 開発チームより愛を込めて</strong>}
      onUnlock={() => console.log("unlocked!")}
    >
      {children}
    </CheatCode>
  )
}

// nuxt/src/demo/usage/effects/CheatCode.vue
<script setup lang="ts">
import CheatCode from "@/components/draft/effects/CheatCode.vue"
// ↑↑↓↓←→←→BA (コナミコマンド) を入力すると紙吹雪と秘密のバナーを出す。code を省略するとコナミコマンド。
const code = ["ArrowUp", "ArrowUp", "ArrowDown", "ArrowDown", "b", "a"]
</script>

<template>
  <CheatCode :code="code" @unlock="() => console.log('unlocked!')">
    <slot />
    <template #secret="{ close }">
      <strong>🎮 開発チームより愛を込めて</strong>
      <v-btn size="small" @click="close">閉じる</v-btn>
    </template>
  </CheatCode>
</template>
