// nuxt/src/pages/form/checkbox.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { countBetween, toggleInList } from "@/utils/draft"
import { useForm } from "@/composables/draft/useForm"
import { HOBBIES } from "@demo-data"
import FormShell from "@/demo/FormShell.vue"
import { fakeSave } from "@/demo/fakeSave"

type Values = { hobbies: string[]; newsletter: boolean; agree: boolean }
const initial: Values = { hobbies: [], newsletter: true, agree: false }
const ORDER = HOBBIES.map((h) => h.value as string)

const saved = ref<Values | null>(null)
const { state, controller: form } = useForm<Values>({
  initial,
  rules: {
    hobbies: countBetween(1, 3, "1〜3 個選んでください"),
    agree: (v) => (v ? null : "同意が必要です"),
  },
  onSubmit: async (v) => {
    await fakeSave()
    saved.value = v
  },
})
const hobbies = computed(() => state.value.values.hobbies)
const all = computed(() => hobbies.value.length === ORDER.length)
const some = computed(() => hobbies.value.length > 0 && !all.value)
const err = (k: keyof Values) => {
  void state.value
  return form.fieldError(k)
}
const toggle = (v: string) => {
  form.setValue("hobbies", toggleInList(hobbies.value, v, ORDER))
  form.touch("hobbies")
}
const toggleAll = () => {
  form.setValue("hobbies", all.value ? [] : [...ORDER])
  form.touch("hobbies")
}
</script>

<template>
  <FormShell
    title="☑️ チェックボックス"
    description="チェックした物を配列 (リスト) で持つ。並びはチェックした順ではなく選択肢の順に揃える (toggleInList)。「すべて」は一部だけ選ぶと中間の表示になる。"
    :form="form"
    :state="state"
    :saved="saved"
  >
    <fieldset class="border-0">
      <legend :class="err('hobbies') ? 'text-error' : 'text-medium-emphasis'">
        趣味 (1〜3 個)
      </legend>
      <v-checkbox
        label="すべて"
        :model-value="all"
        :indeterminate="some"
        hide-details
        density="compact"
        @update:model-value="toggleAll"
      />
      <div class="d-flex flex-wrap pl-6">
        <v-checkbox
          v-for="h in HOBBIES"
          :key="h.value"
          :label="h.label"
          :model-value="hobbies.includes(h.value)"
          hide-details
          density="compact"
          class="mr-4"
          @update:model-value="toggle(h.value)"
        />
      </div>
      <div :class="['text-caption', err('hobbies') ? 'text-error' : 'text-medium-emphasis']">
        {{ err("hobbies") ?? `選んだもの: ${hobbies.length ? hobbies.join(", ") : "なし"}` }}
      </div>
    </fieldset>

    <v-switch
      label="お知らせメールを受け取る"
      color="primary"
      :model-value="state.values.newsletter"
      hide-details
      @update:model-value="(v) => form.setValue('newsletter', !!v)"
    />
    <v-checkbox
      label="利用規約に同意する"
      :model-value="state.values.agree"
      :error-messages="err('agree') ?? undefined"
      @update:model-value="
        (v) => {
          form.setValue('agree', !!v)
          form.touch('agree')
        }
      "
    />
  </FormShell>
</template>

// react/src/pages/form/checkbox.tsx
import { useState } from "react"
import {
  Checkbox,
  FormControl,
  FormControlLabel,
  FormGroup,
  FormHelperText,
  FormLabel,
  Stack,
  Switch,
} from "@mui/material"
import { countBetween, toggleInList } from "@/utils/draft"
import { useForm } from "@/hooks/draft/useForm"
import { HOBBIES } from "@demo-data"
import { FormShell, fakeSave } from "@/demo/FormShell"

type Values = { hobbies: string[]; newsletter: boolean; agree: boolean }
const initial: Values = { hobbies: [], newsletter: true, agree: false }
const ORDER = HOBBIES.map((h) => h.value as string)

export default function CheckboxPage() {
  const [saved, setSaved] = useState<Values | null>(null)
  const { state, controller: form } = useForm<Values>({
    initial,
    rules: {
      hobbies: countBetween(1, 3, "1〜3 個選んでください"),
      agree: (v) => (v ? null : "同意が必要です"),
    },
    onSubmit: async (v) => {
      await fakeSave()
      setSaved(v)
    },
  })
  const { hobbies } = state.values
  const all = hobbies.length === ORDER.length
  const some = hobbies.length > 0 && !all

  return (
    <FormShell
      title="☑️ チェックボックス"
      description="チェックした物を配列 (リスト) で持つ。並びはチェックした順ではなく選択肢の順に揃える (toggleInList)。「すべて」は一部だけ選ぶと中間の表示になる。"
      form={form}
      state={state}
      saved={saved}
    >
      <FormControl error={form.fieldError("hobbies") !== null} component="fieldset">
        <FormLabel component="legend">趣味 (1〜3 個)</FormLabel>
        <FormControlLabel
          label="すべて"
          control={
            <Checkbox
              checked={all}
              indeterminate={some}
              onChange={() => {
                form.setValue("hobbies", all ? [] : [...ORDER])
                form.touch("hobbies")
              }}
            />
          }
        />
        <FormGroup row sx={{ pl: 3 }}>
          {HOBBIES.map((h) => (
            <FormControlLabel
              key={h.value}
              label={h.label}
              control={
                <Checkbox
                  checked={hobbies.includes(h.value)}
                  onChange={() => {
                    form.setValue("hobbies", toggleInList(hobbies, h.value as string, ORDER))
                    form.touch("hobbies")
                  }}
                />
              }
            />
          ))}
        </FormGroup>
        <FormHelperText>
          {form.fieldError("hobbies") ??
            `選んだもの: ${hobbies.length ? hobbies.join(", ") : "なし"}`}
        </FormHelperText>
      </FormControl>

      <Stack>
        <FormControlLabel
          label="お知らせメールを受け取る"
          control={
            <Switch
              checked={state.values.newsletter}
              onChange={(e) => form.setValue("newsletter", e.target.checked)}
            />
          }
        />
        <FormControl error={form.fieldError("agree") !== null}>
          <FormControlLabel
            label="利用規約に同意する"
            control={
              <Checkbox
                checked={state.values.agree}
                onChange={(e) => {
                  form.setValue("agree", e.target.checked)
                  form.touch("agree")
                }}
              />
            }
          />
          <FormHelperText>{form.fieldError("agree") ?? " "}</FormHelperText>
        </FormControl>
      </Stack>
    </FormShell>
  )
}
