// nuxt/src/pages/form/select.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { countBetween, required } from "@/utils/draft"
import { useForm } from "@/composables/draft/useForm"
import { PREFECTURES, REGIONS } from "@demo-data"
import FormShell from "@/demo/FormShell.vue"
import { fakeSave } from "@/demo/fakeSave"

type Values = { region: string; pref: string; visited: string[] }
const initial: Values = { region: "", pref: "", visited: [] }

const saved = ref<Values | null>(null)
const { state, controller: form } = useForm<Values>({
  initial,
  rules: {
    region: required("地方を選んでください"),
    // 他の項目を見る検査: 選んだ都道府県が地方と合っているか
    pref: [
      required("都道府県を選んでください"),
      (code, v) =>
        PREFECTURES.find((p) => p.code === code)?.region === v.region
          ? null
          : "地方と合っていません",
    ],
    visited: countBetween(1, 5, "行ったことのある所を 1〜5 個選んでください"),
  },
  onSubmit: async (v) => {
    await fakeSave()
    saved.value = v
  },
})
const err = (k: keyof Values) => {
  void state.value // state を読んで、変化で描き直す
  return form.fieldError(k) ?? undefined
}
const prefItems = computed(() =>
  PREFECTURES.filter((p) => p.region === state.value.values.region).map((p) => ({
    title: p.name,
    value: p.code,
  })),
)
// 複数選択は地方ごとの見出しつき
const visitedItems = REGIONS.flatMap((r) => [
  { type: "subheader", title: r },
  ...PREFECTURES.filter((p) => p.region === r).map((p) => ({ title: p.name, value: p.code })),
])
const onRegion = (r: string) => {
  form.setValue("region", r)
  form.setValue("pref", "") // 地方を変えたら都道府県は選び直し
}
</script>

<template>
  <FormShell
    title="🔽 セレクト"
    description="地方を選ぶと都道府県の候補が絞られる (連動するセレクト)。複数選択はチップで出す。"
    :form="form"
    :state="state"
    :saved="saved"
  >
    <v-row density="compact">
      <v-col cols="12" sm="6">
        <v-select
          label="地方 *"
          :items="REGIONS"
          :model-value="state.values.region || null"
          :error-messages="err('region')"
          @update:model-value="onRegion"
          @blur="form.touch('region')"
        />
      </v-col>
      <v-col cols="12" sm="6">
        <v-select
          label="都道府県 *"
          :items="prefItems"
          :disabled="!state.values.region"
          :model-value="state.values.pref || null"
          :error-messages="err('pref')"
          :hint="state.values.region ? '' : '先に地方を選ぶ'"
          persistent-hint
          @update:model-value="(v: string) => form.setValue('pref', v)"
          @blur="form.touch('pref')"
        />
      </v-col>
    </v-row>
    <v-select
      label="行ったことのある所 (複数)"
      :items="visitedItems"
      multiple
      chips
      closable-chips
      :model-value="state.values.visited"
      :error-messages="err('visited')"
      :hint="`${state.values.visited.length} / 5 個`"
      persistent-hint
      @update:model-value="(v: string[]) => form.setValue('visited', v)"
      @update:menu="(open: boolean) => !open && form.touch('visited')"
    />
  </FormShell>
</template>

// react/src/pages/form/select.tsx
import { useState } from "react"
import {
  Box,
  Chip,
  FormControl,
  FormHelperText,
  InputLabel,
  ListSubheader,
  MenuItem,
  Select,
  Stack,
} from "@mui/material"
import { countBetween, required } from "@/utils/draft"
import { useForm } from "@/hooks/draft/useForm"
import { PREFECTURES, REGIONS } from "@demo-data"
import { FormShell, fakeSave } from "@/demo/FormShell"

type Values = { region: string; pref: string; visited: string[] }
const initial: Values = { region: "", pref: "", visited: [] }
const nameOf = (code: string) => PREFECTURES.find((p) => p.code === code)?.name ?? code

export default function SelectPage() {
  const [saved, setSaved] = useState<Values | null>(null)
  const { state, controller: form } = useForm<Values>({
    initial,
    rules: {
      region: required("地方を選んでください"),
      // 他の項目を見る検査: 選んだ都道府県が地方と合っているか
      pref: [
        required("都道府県を選んでください"),
        (code, v) =>
          PREFECTURES.find((p) => p.code === code)?.region === v.region
            ? null
            : "地方と合っていません",
      ],
      visited: countBetween(1, 5, "行ったことのある所を 1〜5 個選んでください"),
    },
    onSubmit: async (v) => {
      await fakeSave()
      setSaved(v)
    },
  })
  const err = (k: keyof Values) => form.fieldError(k)

  return (
    <FormShell
      title="🔽 セレクト"
      description="地方を選ぶと都道府県の候補が絞られる (連動するセレクト)。複数選択はチップで出す。"
      form={form}
      state={state}
      saved={saved}
    >
      <Stack direction={{ xs: "column", sm: "row" }} spacing={2}>
        <FormControl fullWidth required error={err("region") !== null}>
          <InputLabel>地方</InputLabel>
          <Select
            label="地方"
            value={state.values.region}
            onChange={(e) => {
              form.setValue("region", e.target.value)
              form.setValue("pref", "") // 地方を変えたら都道府県は選び直し
            }}
            onBlur={() => form.touch("region")}
          >
            {REGIONS.map((r) => (
              <MenuItem key={r} value={r}>
                {r}
              </MenuItem>
            ))}
          </Select>
          <FormHelperText>{err("region") ?? " "}</FormHelperText>
        </FormControl>
        <FormControl
          fullWidth
          required
          error={err("pref") !== null}
          disabled={!state.values.region}
        >
          <InputLabel>都道府県</InputLabel>
          <Select
            label="都道府県"
            value={state.values.pref}
            onChange={(e) => form.setValue("pref", e.target.value)}
            onBlur={() => form.touch("pref")}
          >
            {PREFECTURES.filter((p) => p.region === state.values.region).map((p) => (
              <MenuItem key={p.code} value={p.code}>
                {p.name}
              </MenuItem>
            ))}
          </Select>
          <FormHelperText>
            {err("pref") ?? (state.values.region ? " " : "先に地方を選ぶ")}
          </FormHelperText>
        </FormControl>
      </Stack>

      <FormControl fullWidth error={err("visited") !== null}>
        <InputLabel>行ったことのある所 (複数)</InputLabel>
        <Select
          multiple
          label="行ったことのある所 (複数)"
          value={state.values.visited}
          onChange={(e) => form.setValue("visited", e.target.value as string[])}
          onClose={() => form.touch("visited")}
          renderValue={(codes) => (
            <Box sx={{ display: "flex", flexWrap: "wrap", gap: 0.5 }}>
              {codes.map((c) => (
                <Chip key={c} size="small" label={nameOf(c)} />
              ))}
            </Box>
          )}
          MenuProps={{ slotProps: { paper: { sx: { maxHeight: 360 } } } }}
        >
          {REGIONS.flatMap((r) => [
            <ListSubheader key={`h-${r}`}>{r}</ListSubheader>,
            ...PREFECTURES.filter((p) => p.region === r).map((p) => (
              <MenuItem key={p.code} value={p.code}>
                {p.name}
              </MenuItem>
            )),
          ])}
        </Select>
        <FormHelperText>{err("visited") ?? `${state.values.visited.length} / 5 個`}</FormHelperText>
      </FormControl>
    </FormShell>
  )
}
