// nuxt/src/pages/effects/shatter.vue
<script setup lang="ts">
import ShatterGlass from "@/components/draft/effects/ShatterGlass.vue"
import DemoPage from "@/demo/DemoPage.vue"

const on = () => console.log("smash! 💥")
</script>

<template>
  <ShatterGlass @shatter="on">
    <DemoPage hint="どこかをクリックすると、その場所からガラスのように割れます。" />
  </ShatterGlass>
</template>

// react/src/pages/effects/shatter.tsx
import { ShatterGlass } from "@/components/draft/effects/ShatterGlass"
import { DemoPage } from "@/demo/DemoPage"

export default function ShatterPage() {
  return (
    <ShatterGlass onShatter={() => console.log("smash! 💥")}>
      <DemoPage hint="どこかをクリックすると、その場所からガラスのように割れます。" />
    </ShatterGlass>
  )
}
