// nuxt/src/pages/csv-json/tests.vue
<script setup lang="ts">
// CSV/TSV のテスト結果とカバレッジ (pnpm csv:report が書いた JSON をそのまま描く)。
import {
  COVERAGE_METRICS,
  CSV_REPORT as r,
  CSV_TEST_FILE_LABELS,
  CSV_TEST_FILES,
  formatReportTime,
  groupTests,
} from "@demo-data"

const ok = r.totals.failed === 0
const rows = [...r.coverage.files, { file: "合計", ...r.coverage.total }]
const passedIn = (f: (typeof r.files)[number]) =>
  f.tests.filter((t) => t.status === "passed").length
</script>

<template>
  <div class="d-flex flex-column ga-6">
    <div class="d-flex flex-wrap align-center ga-2">
      <v-chip :color="ok ? 'success' : 'error'" variant="flat">
        {{
          ok
            ? `✅ ${r.totals.passed} / ${r.totals.tests} 件すべて成功`
            : `❌ ${r.totals.failed} 件失敗`
        }}
      </v-chip>
      <v-chip variant="outlined">
        カバレッジ 行 {{ r.coverage.total.lines.pct }}% ・ 分岐 {{ r.coverage.total.branches.pct }}%
      </v-chip>
      <v-chip variant="outlined"
        >{{ r.totals.files }} ファイル ・ {{ r.totals.durationMs }} ms</v-chip
      >
      <span class="text-body-2 text-medium-emphasis">
        {{ formatReportTime(r.generatedAt) }} に実行 (commit {{ r.commit
        }}{{ r.dirty ? " + 未コミットの変更" : "" }})
      </span>
    </div>

    <div>
      <div class="text-h6 mb-2">カバレッジ (本体のコード)</div>
      <v-card border flat>
        <v-table density="compact">
          <thead>
            <tr>
              <th>ファイル</th>
              <th v-for="m in COVERAGE_METRICS" :key="m.key">{{ m.label }}</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="f in rows" :key="f.file">
              <td :class="{ 'font-weight-bold': f.file === '合計' }">{{ f.file }}</td>
              <td v-for="m in COVERAGE_METRICS" :key="m.key" style="min-width: 120px">
                <div class="text-body-2">
                  {{ f[m.key].pct }}% ({{ f[m.key].covered }}/{{ f[m.key].total }})
                </div>
                <v-progress-linear
                  :model-value="f[m.key].pct"
                  :color="f[m.key].pct === 100 ? 'success' : 'warning'"
                />
              </td>
            </tr>
          </tbody>
        </v-table>
      </v-card>
    </div>

    <div>
      <div class="text-h6 mb-2">テストの一覧</div>
      <v-expansion-panels multiple variant="accordion">
        <v-expansion-panel v-for="f in CSV_TEST_FILES" :key="f.file">
          <v-expansion-panel-title>
            <div>
              <div class="font-weight-bold">
                {{ passedIn(f) === f.tests.length ? "✅" : "❌" }}
                {{ CSV_TEST_FILE_LABELS[f.file] ?? f.file }}
              </div>
              <div class="text-body-2 text-medium-emphasis">
                {{ f.file }} ・ {{ passedIn(f) }} / {{ f.tests.length }} 件
              </div>
            </div>
          </v-expansion-panel-title>
          <v-expansion-panel-text>
            <div v-for="g in groupTests(f.tests)" :key="g.title" class="mb-4">
              <div class="text-subtitle-2 mb-1">{{ g.title }}</div>
              <div v-for="t in g.items" :key="t.title" class="text-body-2 pl-4">
                {{ t.status === "passed" ? "✓" : "✗" }} {{ t.title }}
                <div v-if="t.failure" class="text-error pl-4">{{ t.failure }}</div>
              </div>
            </div>
          </v-expansion-panel-text>
        </v-expansion-panel>
      </v-expansion-panels>
    </div>
  </div>
</template>

// react/src/pages/csv-json/tests.tsx
import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Box,
  Chip,
  LinearProgress,
  Paper,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  Typography,
} from "@mui/material"
import ExpandMoreIcon from "@mui/icons-material/ExpandMore"
import {
  COVERAGE_METRICS,
  CSV_REPORT as r,
  CSV_TEST_FILE_LABELS,
  CSV_TEST_FILES,
  formatReportTime,
  groupTests,
} from "@demo-data"

/** CSV/TSV のテスト結果とカバレッジ (pnpm csv:report が書いた JSON をそのまま描く)。 */
export default function CsvTestsPage() {
  const ok = r.totals.failed === 0
  return (
    <Stack spacing={3}>
      <Stack direction="row" spacing={1} sx={{ flexWrap: "wrap", alignItems: "center", rowGap: 1 }}>
        <Chip
          color={ok ? "success" : "error"}
          label={
            ok
              ? `✅ ${r.totals.passed} / ${r.totals.tests} 件すべて成功`
              : `❌ ${r.totals.failed} 件失敗`
          }
        />
        <Chip
          variant="outlined"
          label={`カバレッジ 行 ${r.coverage.total.lines.pct}% ・ 分岐 ${r.coverage.total.branches.pct}%`}
        />
        <Chip
          variant="outlined"
          label={`${r.totals.files} ファイル ・ ${r.totals.durationMs} ms`}
        />
        <Typography variant="body2" color="text.secondary">
          {formatReportTime(r.generatedAt)} に実行 (commit {r.commit}
          {r.dirty ? " + 未コミットの変更" : ""})
        </Typography>
      </Stack>

      <Box>
        <Typography variant="h6" sx={{ mb: 1 }}>
          カバレッジ (本体のコード)
        </Typography>
        <Paper variant="outlined" sx={{ overflowX: "auto" }}>
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell>ファイル</TableCell>
                {COVERAGE_METRICS.map((m) => (
                  <TableCell key={m.key}>{m.label}</TableCell>
                ))}
              </TableRow>
            </TableHead>
            <TableBody>
              {[...r.coverage.files, { file: "合計", ...r.coverage.total }].map((f) => (
                <TableRow key={f.file}>
                  <TableCell sx={{ fontWeight: f.file === "合計" ? 700 : 400 }}>{f.file}</TableCell>
                  {COVERAGE_METRICS.map((m) => (
                    <TableCell key={m.key} sx={{ minWidth: 120 }}>
                      <Typography variant="body2">
                        {f[m.key].pct}% ({f[m.key].covered}/{f[m.key].total})
                      </Typography>
                      <LinearProgress
                        variant="determinate"
                        value={f[m.key].pct}
                        color={f[m.key].pct === 100 ? "success" : "warning"}
                      />
                    </TableCell>
                  ))}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Paper>
      </Box>

      <Box>
        <Typography variant="h6" sx={{ mb: 1 }}>
          テストの一覧
        </Typography>
        {CSV_TEST_FILES.map((f) => {
          const passed = f.tests.filter((t) => t.status === "passed").length
          return (
            <Accordion key={f.file} disableGutters variant="outlined">
              <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                <Stack>
                  <Typography sx={{ fontWeight: 600 }}>
                    {passed === f.tests.length ? "✅" : "❌"}{" "}
                    {CSV_TEST_FILE_LABELS[f.file] ?? f.file}
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    {f.file} ・ {passed} / {f.tests.length} 件
                  </Typography>
                </Stack>
              </AccordionSummary>
              <AccordionDetails>
                {groupTests(f.tests).map((g) => (
                  <Box key={g.title} sx={{ mb: 2 }}>
                    <Typography variant="subtitle2" sx={{ mb: 0.5 }}>
                      {g.title}
                    </Typography>
                    {g.items.map((t) => (
                      <Typography key={t.title} variant="body2" sx={{ pl: 2 }}>
                        {t.status === "passed" ? "✓" : "✗"} {t.title}
                        {t.failure && (
                          <Box
                            component="span"
                            sx={{ color: "error.main", display: "block", pl: 2 }}
                          >
                            {t.failure}
                          </Box>
                        )}
                      </Typography>
                    ))}
                  </Box>
                ))}
              </AccordionDetails>
            </Accordion>
          )
        })}
      </Box>
    </Stack>
  )
}
