// react/src/components/DialogHost.tsx
import {
  Alert,
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  TextField,
  useMediaQuery,
  useTheme,
} from "@mui/material"
import { useStore } from "@/hooks/useStore"
import type { DialogEntry, DialogsController } from "@core"

export interface DialogHostProps {
  /** @core の createDialogs() で作ったもの (アプリで 1 つ作って使い回す)。 */
  dialogs: DialogsController
}

/**
 * createDialogs で開いた確認・お知らせ・入力のダイアログを描く (MUI)。アプリのどこか 1 か所に置く。
 * 開く・閉じる・送信中・エラーはすべてコア側が持ち、ここは stack を描くだけ。
 */
export function DialogHost({ dialogs }: DialogHostProps) {
  const { stack } = useStore(dialogs)
  return (
    <>
      {stack.map((d) => (
        <OneDialog key={d.id} entry={d} dialogs={dialogs} />
      ))}
    </>
  )
}

function OneDialog({ entry: d, dialogs }: { entry: DialogEntry; dialogs: DialogsController }) {
  const theme = useTheme()
  // 狭い画面では全画面にする (入力欄があるとき特に使いやすい)
  const fullScreen = useMediaQuery(theme.breakpoints.down("sm")) && d.kind === "prompt"
  return (
    <Dialog
      open
      fullScreen={fullScreen}
      fullWidth
      maxWidth="xs"
      onClose={() => dialogs.dismiss(d.id)}
      aria-labelledby={`hc-dialog-${d.id}`}
    >
      <DialogTitle id={`hc-dialog-${d.id}`}>{d.title}</DialogTitle>
      <DialogContent>
        {d.message && (
          <DialogContentText sx={{ whiteSpace: "pre-wrap" }}>{d.message}</DialogContentText>
        )}
        {d.input && (
          <TextField
            autoFocus
            fullWidth
            margin="dense"
            label={d.input.label}
            placeholder={d.input.placeholder}
            value={d.input.value}
            onChange={(e) => dialogs.setInput(d.id, e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.nativeEvent.isComposing) void dialogs.accept(d.id)
            }}
            error={d.input.error !== null && d.input.value !== ""}
            helperText={d.input.value !== "" ? (d.input.error ?? " ") : " "}
            disabled={d.busy}
          />
        )}
        {d.error && (
          <Alert severity="error" sx={{ mt: 2 }}>
            {d.error}
          </Alert>
        )}
      </DialogContent>
      <DialogActions>
        {d.cancelLabel && (
          <Button onClick={() => dialogs.dismiss(d.id)} disabled={d.busy}>
            {d.cancelLabel}
          </Button>
        )}
        <Button
          variant="contained"
          color={d.danger ? "error" : "primary"}
          onClick={() => void dialogs.accept(d.id)}
          loading={d.busy}
          disabled={d.input?.error != null}
          autoFocus={!d.input}
        >
          {d.error ? "もう一度" : d.okLabel}
        </Button>
      </DialogActions>
    </Dialog>
  )
}

// packages/vuetify/src/DialogHost.vue
<script setup lang="ts">
// createDialogs で開いた確認・お知らせ・入力のダイアログを描く (Vuetify)。アプリのどこか 1 か所に置く。
// 開く・閉じる・送信中・エラーはすべてコア側が持ち、ここは stack を描くだけ (React 版の DialogHost と同じ)。
import { useDisplay } from "vuetify"
import type { DialogsController } from "@hc/core"
import { useStore } from "@hc/vue"

const props = defineProps<{
  /** @hc/core の createDialogs() で作ったもの (アプリで 1 つ作って使い回す)。 */
  dialogs: DialogsController
}>()
const state = useStore(props.dialogs)
const { smAndDown } = useDisplay()
const onEnter = (id: number, e: KeyboardEvent) => {
  if (!e.isComposing) void props.dialogs.accept(id)
}
</script>

<template>
  <v-dialog
    v-for="d in state.stack"
    :key="d.id"
    :model-value="true"
    max-width="440"
    :fullscreen="smAndDown && d.kind === 'prompt'"
    :persistent="d.busy"
    @update:model-value="(open: boolean) => !open && dialogs.dismiss(d.id)"
  >
    <v-card>
      <!-- 長い題名は折り返す (v-card の title は 1 行で切れるため) -->
      <v-card-title class="text-wrap">{{ d.title }}</v-card-title>
      <v-card-text>
        <p v-if="d.message" class="text-medium-emphasis" style="white-space: pre-wrap">
          {{ d.message }}
        </p>
        <v-text-field
          v-if="d.input"
          autofocus
          class="mt-2"
          :label="d.input.label"
          :placeholder="d.input.placeholder"
          :model-value="d.input.value"
          :error-messages="d.input.value !== '' ? (d.input.error ?? undefined) : undefined"
          :disabled="d.busy"
          @update:model-value="(v: string) => dialogs.setInput(d.id, v)"
          @keydown.enter="(e: KeyboardEvent) => onEnter(d.id, e)"
        />
        <v-alert v-if="d.error" type="error" density="compact" class="mt-2">{{ d.error }}</v-alert>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn v-if="d.cancelLabel" :disabled="d.busy" @click="dialogs.dismiss(d.id)">
          {{ d.cancelLabel }}
        </v-btn>
        <v-btn
          variant="flat"
          :color="d.danger ? 'error' : 'primary'"
          :loading="d.busy"
          :disabled="d.input?.error != null"
          @click="dialogs.accept(d.id)"
        >
          {{ d.error ? "もう一度" : d.okLabel }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>
