// apps/demo-react/src/demos/EmployeesDemo.tsx
import { useMemo } from "react"
import {
  Alert,
  Button,
  CircularProgress,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  IconButton,
  MenuItem,
  Stack,
  TextField,
  Tooltip,
  Typography,
} from "@mui/material"
import RefreshIcon from "@mui/icons-material/Refresh"
import AddIcon from "@mui/icons-material/Add"
import EditIcon from "@mui/icons-material/Edit"
import DeleteIcon from "@mui/icons-material/Delete"
import { DataTable } from "@hc/mui"
import { useController, useStore } from "@hc/react"
import {
  createEmployeeDirectory,
  createEmployeeSource,
  DEPARTMENTS,
  EMPLOYEE_HEADERS as H,
  ROLES,
  STATUS_LABEL,
  type Status,
} from "@hc/demo-data"
import { employeeColumnHelper, employeeColumns } from "./employeeColumns"

/**
 * 全件を分割取得して表に出し、追加・編集・削除する。
 * 画面の状態 (読み込み・ダイアログ・送信中・エラー) は @hc/demo-data の createEmployeeDirectory が持つ。
 */
export function EmployeesDemo() {
  const dir = useController(() => createEmployeeDirectory(createEmployeeSource()))
  const { items, loading, error, form, deleting } = useStore(dir)

  const columns = useMemo(
    () => [
      ...employeeColumns,
      employeeColumnHelper.display({
        id: "actions",
        header: "操作",
        cell: (info) => (
          <Stack direction="row" spacing={0.5}>
            <Tooltip title="編集">
              <IconButton size="small" onClick={() => dir.openEdit(info.row.original)}>
                <EditIcon fontSize="small" />
              </IconButton>
            </Tooltip>
            <Tooltip title="削除">
              <IconButton size="small" onClick={() => dir.askDelete(info.row.original)}>
                <DeleteIcon fontSize="small" />
              </IconButton>
            </Tooltip>
          </Stack>
        ),
      }),
    ],
    [dir],
  )

  if (error) {
    return (
      <Alert
        severity="error"
        action={
          <Button color="inherit" size="small" onClick={() => void dir.reload()}>
            再試行
          </Button>
        }
      >
        {error}
      </Alert>
    )
  }

  return (
    <Stack spacing={1}>
      <Stack direction="row" sx={{ alignItems: "center", justifyContent: "space-between" }}>
        <Typography variant="body2" color="text.secondary">
          ブラウザ内の模擬 API から 25 件ずつ全件を取得して、並べ替え・検索・ページングは手元で行う
        </Typography>
        <Stack direction="row" spacing={1}>
          <Button
            size="small"
            startIcon={<RefreshIcon />}
            onClick={() => void dir.reload()}
            disabled={loading}
          >
            再取得
          </Button>
          <Button size="small" variant="contained" startIcon={<AddIcon />} onClick={dir.openCreate}>
            追加
          </Button>
        </Stack>
      </Stack>

      {loading && items.length === 0 ? (
        <Stack sx={{ py: 8, alignItems: "center" }}>
          <CircularProgress />
        </Stack>
      ) : (
        <DataTable
          data={items}
          columns={columns}
          getRowId={(e) => e.email}
          searchPlaceholder="フリーワード検索 (空白で区切ると AND。例: 営業 在籍)"
        />
      )}

      <Dialog open={form !== null} onClose={dir.closeForm} fullWidth maxWidth="sm">
        {form && (
          <>
            <DialogTitle>{form.mode === "create" ? "従業員を追加" : "従業員を編集"}</DialogTitle>
            <DialogContent>
              <Stack spacing={2} sx={{ mt: 1 }}>
                {form.error && <Alert severity="error">{form.error}</Alert>}
                <TextField
                  label={H.email}
                  type="email"
                  value={form.value.email}
                  onChange={(e) => dir.updateForm({ email: e.target.value })}
                  disabled={form.mode === "edit"}
                  helperText={
                    form.mode === "edit" ? "メールアドレスは識別子のため変更できません" : undefined
                  }
                  required
                />
                <TextField
                  label={H.name}
                  value={form.value.name}
                  onChange={(e) => dir.updateForm({ name: e.target.value })}
                  required
                />
                <Stack direction="row" spacing={2}>
                  <TextField
                    select
                    fullWidth
                    label={H.department}
                    value={form.value.department}
                    onChange={(e) => dir.updateForm({ department: e.target.value })}
                  >
                    {DEPARTMENTS.map((d) => (
                      <MenuItem key={d} value={d}>
                        {d}
                      </MenuItem>
                    ))}
                  </TextField>
                  <TextField
                    select
                    fullWidth
                    label={H.role}
                    value={form.value.role}
                    onChange={(e) => dir.updateForm({ role: e.target.value })}
                  >
                    {ROLES.map((r) => (
                      <MenuItem key={r} value={r}>
                        {r}
                      </MenuItem>
                    ))}
                  </TextField>
                </Stack>
                <Stack direction="row" spacing={2}>
                  <TextField
                    select
                    fullWidth
                    label={H.status}
                    value={form.value.status}
                    onChange={(e) => dir.updateForm({ status: e.target.value as Status })}
                  >
                    {Object.entries(STATUS_LABEL).map(([v, l]) => (
                      <MenuItem key={v} value={v}>
                        {l}
                      </MenuItem>
                    ))}
                  </TextField>
                  <TextField
                    fullWidth
                    type="date"
                    label={H.joinedAt}
                    value={form.value.joinedAt}
                    onChange={(e) => dir.updateForm({ joinedAt: e.target.value })}
                    slotProps={{ inputLabel: { shrink: true } }}
                  />
                  <TextField
                    fullWidth
                    type="number"
                    label={H.salary}
                    value={form.value.salary}
                    onChange={(e) => dir.updateForm({ salary: Number(e.target.value) })}
                  />
                </Stack>
              </Stack>
            </DialogContent>
            <DialogActions>
              <Button onClick={dir.closeForm} disabled={form.submitting}>
                キャンセル
              </Button>
              <Button
                variant="contained"
                onClick={() => void dir.submitForm()}
                disabled={form.submitting}
              >
                {form.mode === "create" ? "追加" : "保存"}
              </Button>
            </DialogActions>
          </>
        )}
      </Dialog>

      <Dialog open={deleting !== null} onClose={dir.cancelDelete}>
        <DialogTitle>従業員を削除しますか？</DialogTitle>
        <DialogContent>
          <DialogContentText>
            {deleting?.employee.name}（{deleting?.employee.email}
            ）を削除します。この操作は元に戻せません。
          </DialogContentText>
          {deleting?.error && (
            <Alert severity="error" sx={{ mt: 2 }}>
              {deleting.error}
            </Alert>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={dir.cancelDelete} disabled={deleting?.submitting}>
            キャンセル
          </Button>
          <Button
            onClick={() => void dir.confirmDelete()}
            color="error"
            disabled={deleting?.submitting}
          >
            削除
          </Button>
        </DialogActions>
      </Dialog>
    </Stack>
  )
}

// apps/demo-vue/src/demos/EmployeesDemo.vue
<script setup lang="ts">
// 全件を分割取得して表に出し、追加・編集・削除する。
// 画面の状態 (読み込み・ダイアログ・送信中・エラー) は @hc/demo-data の createEmployeeDirectory が持つ。
import { h } from "vue"
import { VBtn } from "vuetify/components"
import { DataTable } from "@hc/vuetify"
import { useStore } from "@hc/vue"
import {
  createEmployeeDirectory,
  createEmployeeSource,
  DEPARTMENTS,
  EMPLOYEE_HEADERS as H,
  ROLES,
  STATUS_LABEL,
  type Employee,
} from "@hc/demo-data"
import { employeeColumnHelper, employeeColumns } from "./employeeColumns"

const dir = createEmployeeDirectory(createEmployeeSource())
const state = useStore(dir)

const columns = [
  ...employeeColumns,
  employeeColumnHelper.display({
    id: "actions",
    header: "操作",
    cell: (info) =>
      h("div", { class: "d-flex ga-1" }, [
        h(VBtn, {
          icon: "mdi-pencil",
          size: "x-small",
          variant: "text",
          title: "編集",
          onClick: () => dir.openEdit(info.row.original),
        }),
        h(VBtn, {
          icon: "mdi-delete",
          size: "x-small",
          variant: "text",
          title: "削除",
          onClick: () => dir.askDelete(info.row.original),
        }),
      ]),
  }),
]

// 読み取り専用タプルのままだと v-select が値を狭い型で推論するので string[] にしておく。
const departments: string[] = [...DEPARTMENTS]
const roles: string[] = [...ROLES]
const statusItems = Object.entries(STATUS_LABEL).map(([value, title]) => ({ value, title }))
const rowId = (e: Employee) => e.email
</script>

<template>
  <v-alert v-if="state.error" type="error" variant="tonal">
    {{ state.error }}
    <template #append>
      <v-btn size="small" variant="text" @click="dir.reload()">再試行</v-btn>
    </template>
  </v-alert>
  <div v-else>
    <div class="head mb-2">
      <span class="text-body-2 text-medium-emphasis">
        ブラウザ内の模擬 API から 25 件ずつ全件を取得して、並べ替え・検索・ページングは手元で行う
      </span>
      <div class="d-flex ga-2">
        <v-btn
          size="small"
          variant="text"
          prepend-icon="mdi-refresh"
          :disabled="state.loading"
          @click="dir.reload()"
        >
          再取得
        </v-btn>
        <v-btn size="small" color="primary" prepend-icon="mdi-plus" @click="dir.openCreate()">
          追加
        </v-btn>
      </div>
    </div>

    <div v-if="state.loading && state.items.length === 0" class="d-flex justify-center py-16">
      <v-progress-circular indeterminate />
    </div>
    <DataTable
      v-else
      :data="state.items"
      :columns="columns"
      :get-row-id="rowId"
      search-placeholder="フリーワード検索 (空白で区切ると AND。例: 営業 在籍)"
    />

    <v-dialog
      :model-value="state.form !== null"
      max-width="600"
      @update:model-value="dir.closeForm()"
    >
      <v-card
        v-if="state.form"
        :title="state.form.mode === 'create' ? '従業員を追加' : '従業員を編集'"
      >
        <v-card-text class="d-flex flex-column ga-3">
          <v-alert v-if="state.form.error" type="error" variant="tonal" density="compact">
            {{ state.form.error }}
          </v-alert>
          <v-text-field
            :label="H.email"
            type="email"
            :model-value="state.form.value.email"
            :disabled="state.form.mode === 'edit'"
            :hint="
              state.form.mode === 'edit' ? 'メールアドレスは識別子のため変更できません' : undefined
            "
            persistent-hint
            @update:model-value="(v: string) => dir.updateForm({ email: v })"
          />
          <v-text-field
            :label="H.name"
            :model-value="state.form.value.name"
            @update:model-value="(v: string) => dir.updateForm({ name: v })"
          />
          <div class="d-flex ga-3">
            <v-select
              :label="H.department"
              :items="departments"
              :model-value="state.form.value.department"
              @update:model-value="(v: string) => dir.updateForm({ department: v })"
            />
            <v-select
              :label="H.role"
              :items="roles"
              :model-value="state.form.value.role"
              @update:model-value="(v: string) => dir.updateForm({ role: v })"
            />
          </div>
          <div class="d-flex ga-3">
            <v-select
              :label="H.status"
              :items="statusItems"
              :model-value="state.form.value.status"
              @update:model-value="(v: Employee['status']) => dir.updateForm({ status: v })"
            />
            <v-text-field
              :label="H.joinedAt"
              type="date"
              :model-value="state.form.value.joinedAt"
              @update:model-value="(v: string) => dir.updateForm({ joinedAt: v })"
            />
            <v-text-field
              :label="H.salary"
              type="number"
              :model-value="state.form.value.salary"
              @update:model-value="(v: string) => dir.updateForm({ salary: Number(v) })"
            />
          </div>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn :disabled="state.form.submitting" @click="dir.closeForm()">キャンセル</v-btn>
          <v-btn
            color="primary"
            variant="flat"
            :loading="state.form.submitting"
            @click="dir.submitForm()"
          >
            {{ state.form.mode === "create" ? "追加" : "保存" }}
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-dialog
      :model-value="state.deleting !== null"
      max-width="480"
      @update:model-value="dir.cancelDelete()"
    >
      <v-card v-if="state.deleting" title="従業員を削除しますか？">
        <v-card-text>
          {{ state.deleting.employee.name }}（{{
            state.deleting.employee.email
          }}）を削除します。この操作は元に戻せません。
          <v-alert
            v-if="state.deleting.error"
            type="error"
            variant="tonal"
            density="compact"
            class="mt-3"
          >
            {{ state.deleting.error }}
          </v-alert>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn :disabled="state.deleting.submitting" @click="dir.cancelDelete()"
            >キャンセル</v-btn
          >
          <v-btn color="error" :loading="state.deleting.submitting" @click="dir.confirmDelete()">
            削除
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>

<style scoped>
.head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
}
</style>
