// nuxt/src/components/effects/CheatCode.vue
<script setup lang="ts">
// 隠しコマンド (↑ ↑ ↓ ↓ ← → ← → B A) で解除されるイースターエッグ (Vuetify)。
// キー照合・効果音・紙吹雪・きらめきは @core の createCheatCode が持ち、ここは
// host 要素と秘密のバナーを描くだけ。包む中身は default スロット、秘密は secret スロットで差し替える。
import { ref, watch } from "vue"
import {
  CHEAT_POP_ANIMATION,
  CHEAT_SECRET_Z_INDEX,
  CHEAT_SEQUENCE,
  createCheatCode,
  type CheatCodeOptions,
} from "@core"
import { useMounted } from "@/composables/useMounted"
import { useStore } from "@/composables/useStore"

const props = withDefaults(
  defineProps<{
    /** キー入力シーケンスを上書きする (KeyboardEvent.key の値、大文字小文字は無視)。 */
    code?: readonly string[]
    /** 解除時に紙吹雪を降らせる。 */
    confetti?: boolean
    /** 解除時にページ全体へ短い虹色のきらめきをかける。 */
    shimmer?: boolean
    /** 解除時に合成したパワーアップ音を鳴らす。 */
    sound?: boolean
    /** 2 回目の入力で解除を切り替えず、解除したままにする。 */
    sticky?: boolean
  }>(),
  { code: () => CHEAT_SEQUENCE, confetti: true, shimmer: true, sound: true, sticky: false },
)
/** unlock: コードが完成するたびに発火する (React 版の onUnlock)。 */
const emit = defineEmits<{ unlock: [] }>()
defineSlots<{
  default?: () => unknown
  /** 解除されたときに表示する内容。省略時はお祝いのバナー。 */
  secret?: (props: { close: () => void }) => unknown
}>()

const root = ref<HTMLElement | null>(null)
const content = ref<HTMLElement | null>(null)
const overlay = ref<HTMLElement | null>(null)

const options = (): CheatCodeOptions => ({
  code: props.code,
  confetti: props.confetti,
  shimmer: props.shimmer,
  sound: props.sound,
  sticky: props.sticky,
  onUnlock: () => emit("unlock"),
})

const controller = useMounted(() =>
  root.value && content.value && overlay.value
    ? createCheatCode(
        { root: root.value, content: content.value, overlay: overlay.value },
        options(),
      )
    : null,
)
// props の差し替えはコントローラを作りなおさずに反映する (code が変われば進み具合はリセット)。
watch(
  () => [props.code.join("\u0000"), props.confetti, props.shimmer, props.sound, props.sticky],
  () => controller.value?.setOptions(options()),
)
const state = useStore(controller)
const close = () => controller.value?.close()
</script>

<template>
  <div ref="root" class="cheat-code">
    <div ref="content"><slot /></div>
    <!-- 紙吹雪のレイヤー (中身とスタイルはコントローラが管理する) -->
    <div ref="overlay" />

    <!-- 秘密のコンテンツ -->
    <div v-if="state?.unlocked" class="secret-layer" :style="{ zIndex: CHEAT_SECRET_Z_INDEX }">
      <div class="secret-pop" :style="{ animation: CHEAT_POP_ANIMATION }">
        <slot name="secret" :close="close">
          <v-sheet
            role="dialog"
            aria-label="隠しコマンド成功"
            class="default-secret"
            color="rgba(20,20,30,0.9)"
          >
            <div class="emoji">🎉</div>
            <div class="title">残機 30 機 解除！</div>
            <div class="body">
              隠しコマンド成功。<code>secret</code> スロットで中身を差し替えられます。
            </div>
            <v-btn class="close" color="#6a5cff" rounded="pill" variant="flat" @click="close">
              閉じる (Esc)
            </v-btn>
          </v-sheet>
        </slot>
      </div>
    </div>
  </div>
</template>

<style scoped>
.cheat-code {
  position: relative;
}
.secret-layer {
  position: fixed;
  inset: 0;
  display: grid;
  place-items: center;
  pointer-events: none;
}
.secret-pop {
  pointer-events: auto;
}
.default-secret {
  padding: 28px 36px;
  border-radius: 20px;
  color: #fff;
  font-family: system-ui, sans-serif;
  text-align: center;
  box-shadow: 0 18px 50px rgba(0, 0, 0, 0.5);
  max-width: 360px;
}
.emoji {
  font-size: 44px;
  line-height: 1.2;
}
.title {
  font-size: 24px;
  font-weight: 800;
  margin: 6px 0;
}
.body {
  opacity: 0.8;
  font-size: 14px;
}
.close {
  margin-top: 18px;
  font-weight: 700;
  letter-spacing: normal;
  text-transform: none;
}
</style>

// packages/mui/src/effects/CheatCode.tsx
import { useLayoutEffect, useRef, type ReactNode } from "react"
import { Box, Button, Typography } from "@mui/material"
import {
  CHEAT_POP_ANIMATION,
  CHEAT_SECRET_Z_INDEX,
  CHEAT_SEQUENCE,
  createCheatCode,
} from "@hc/core"
import { useMounted, useStore } from "@hc/react"

export interface CheatCodeProps {
  children: ReactNode
  /** 解除されたときに表示する内容。デフォルトはお祝いのバナー。 */
  secret?: ReactNode
  /** キー入力シーケンスを上書きする (KeyboardEvent.key の値、大文字小文字は無視)。 */
  code?: readonly string[]
  /** 解除時に紙吹雪を降らせる。@default true */
  confetti?: boolean
  /** 解除時にページ全体へ短い虹色のきらめきをかける。@default true */
  shimmer?: boolean
  /** 解除時に合成したパワーアップ音を鳴らす。@default true */
  sound?: boolean
  /** 2 回目の入力で解除を切り替えず、解除したままにする。@default false */
  sticky?: boolean
  /** コードが完成するたびに発火する。 */
  onUnlock?: () => void
}

/**
 * 隠しコマンド (↑ ↑ ↓ ↓ ← → ← → B A) で解除されるイースターエッグ (MUI)。
 * キー照合・効果音・紙吹雪・きらめきは @hc/core の createCheatCode が持ち、ここは
 * host 要素と秘密のバナーを描くだけ。子要素はそのまま描画される。
 */
export function CheatCode({
  children,
  secret,
  code = CHEAT_SEQUENCE,
  confetti = true,
  shimmer = true,
  sound = true,
  sticky = false,
  onUnlock,
}: CheatCodeProps) {
  const rootRef = useRef<HTMLDivElement>(null)
  const contentRef = useRef<HTMLDivElement>(null)
  const overlayRef = useRef<HTMLDivElement>(null)

  // onUnlock は作りなおさずに最新版を呼ぶ。
  const onUnlockRef = useRef(onUnlock)
  useLayoutEffect(() => {
    onUnlockRef.current = onUnlock
  })

  const options = {
    code,
    confetti,
    shimmer,
    sound,
    sticky,
    onUnlock: () => onUnlockRef.current?.(),
  }
  const controller = useMounted(() => {
    const root = rootRef.current
    const content = contentRef.current
    const overlay = overlayRef.current
    if (!root || !content || !overlay) return null
    return createCheatCode({ root, content, overlay }, options)
  }, [])
  // props の差し替えはコントローラを作りなおさずに反映する (code が変われば進み具合はリセット)。
  useLayoutEffect(() => {
    controller?.setOptions(options)
    // eslint-disable-next-line react-hooks/exhaustive-deps -- options は下の値から作る
  }, [controller, code.join("\u0000"), confetti, shimmer, sound, sticky])

  const state = useStore(controller)

  return (
    <div ref={rootRef} style={{ position: "relative" }}>
      <div ref={contentRef}>{children}</div>
      {/* 紙吹雪のレイヤー (中身とスタイルはコントローラが管理する) */}
      <div ref={overlayRef} />

      {/* 秘密のコンテンツ */}
      {state?.unlocked && (
        <Box
          sx={{
            position: "fixed",
            inset: 0,
            display: "grid",
            placeItems: "center",
            pointerEvents: "none",
            zIndex: CHEAT_SECRET_Z_INDEX,
          }}
        >
          <Box sx={{ pointerEvents: "auto", animation: CHEAT_POP_ANIMATION }}>
            {secret ?? <DefaultSecret onClose={() => controller?.close()} />}
          </Box>
        </Box>
      )}
    </div>
  )
}

/** デフォルトのお祝いバナー。 */
function DefaultSecret({ onClose }: { onClose: () => void }) {
  return (
    <Box
      role="dialog"
      aria-label="隠しコマンド成功"
      sx={{
        px: "36px",
        py: "28px",
        borderRadius: "20px",
        bgcolor: "rgba(20,20,30,0.9)",
        color: "#fff",
        textAlign: "center",
        boxShadow: "0 18px 50px rgba(0,0,0,0.5)",
        maxWidth: 360,
      }}
    >
      <Box sx={{ fontSize: 44, lineHeight: 1.2 }}>🎉</Box>
      <Typography sx={{ fontSize: 24, fontWeight: 800, my: "6px" }}>残機 30 機 解除！</Typography>
      <Typography sx={{ opacity: 0.8, fontSize: 14 }}>
        隠しコマンド成功。<code>secret</code> prop で中身を差し替えられます。
      </Typography>
      <Button
        variant="contained"
        disableElevation
        onClick={onClose}
        sx={{
          mt: "18px",
          px: "18px",
          borderRadius: 999,
          bgcolor: "#6a5cff",
          fontWeight: 700,
          textTransform: "none",
          "&:hover": { bgcolor: "#5747f0" },
        }}
      >
        閉じる (Esc)
      </Button>
    </Box>
  )
}

export default CheatCode
