// nuxt/src/components/effects/JigsawPuzzle.vue
<script setup lang="ts">
// 包んだ内容をジグソーパズルにする演出 (Vuetify)。
// ピースの生成・ドラッグ・スナップ・効果音は @core の createJigsaw が持ち、
// ここは host 構造と操作バー (進捗・シャッフル・そろえる) とクリア表示を描くだけ。
import { ref, watch } from "vue"
import { useMounted } from "@/composables/useMounted"
import { useStore } from "@/composables/useStore"
import { createJigsaw } from "@core"

const props = withDefaults(
  defineProps<{
    /** パズルの行数。 */
    rows?: number
    /** パズルの列数。 */
    cols?: number
    /** 効果のオン/オフ。オフのときスロットの内容は通常どおり描かれる。 */
    active?: boolean
    /** ピースをシャッフルした状態でゲームを開始する。 */
    scattered?: boolean
    /** ユーザーがピースをドラッグできるようにする。 */
    draggable?: boolean
    /** フローティングの操作バー（シャッフル / そろえる / 進捗）を表示する。 */
    controls?: boolean
    /** パズルの切り方を変える。 */
    seed?: number
    /** ピースが定位置にはまったときに合成したクリック音を鳴らす。 */
    sound?: boolean
  }>(),
  {
    rows: 4,
    cols: 6,
    active: true,
    scattered: true,
    draggable: true,
    controls: true,
    seed: 1,
    sound: true,
  },
)
/** solved: すべてのピースが定位置に固定されたときに一度だけ発火する。 */
const emit = defineEmits<{ solved: [] }>()

const root = ref<HTMLElement | null>(null)
const content = ref<HTMLElement | null>(null)
const overlay = ref<HTMLElement | null>(null)

// sound は setSound で切り替えるので作りなおしの対象にしない (パズルがばらけ直さないように)。
const controller = useMounted(() => {
  if (!props.active || !root.value || !content.value || !overlay.value) return null
  return createJigsaw(
    { root: root.value, content: content.value, overlay: overlay.value },
    {
      rows: props.rows,
      cols: props.cols,
      seed: props.seed,
      scattered: props.scattered,
      draggable: props.draggable,
      sound: props.sound,
      onSolved: () => emit("solved"),
    },
  )
}, [
  () => props.active,
  () => props.rows,
  () => props.cols,
  () => props.seed,
  () => props.scattered,
  () => props.draggable,
])
watch(
  () => props.sound,
  (on) => controller.value?.setSound(on),
)

const state = useStore(controller)
</script>

<template>
  <div ref="root">
    <div ref="content"><slot /></div>
    <div ref="overlay" />

    <!-- クリア時のバナー -->
    <div v-if="state?.solved" class="jigsaw-banner-wrap">
      <div class="jigsaw-banner">🎉 クリア！</div>
    </div>

    <div v-if="controller && state && controls" class="jigsaw-controls">
      <v-chip size="small" variant="flat" class="jigsaw-count">
        {{ state.placed }} / {{ state.total }}
      </v-chip>
      <v-btn rounded="pill" color="#e8543f" class="jigsaw-btn" @click="controller.shuffle()">
        🔀 シャッフル
      </v-btn>
      <v-btn rounded="pill" color="#2d8f5a" class="jigsaw-btn" @click="controller.solve()">
        🧩 そろえる
      </v-btn>
    </div>
  </div>
</template>

<style scoped>
.jigsaw-banner-wrap {
  position: absolute;
  inset: 0;
  display: grid;
  place-items: center;
  pointer-events: none;
  z-index: 10000;
}
.jigsaw-banner {
  padding: 16px 28px;
  border-radius: 16px;
  background: rgba(20, 20, 30, 0.82);
  color: #fff;
  font-family: system-ui, sans-serif;
  font-size: 28px;
  font-weight: 800;
  letter-spacing: 1px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.45);
}
.jigsaw-controls {
  position: absolute;
  top: 12px;
  right: 12px;
  z-index: 10001;
  display: flex;
  align-items: center;
  gap: 8px;
}
.jigsaw-count {
  background: rgba(20, 20, 30, 0.7) !important;
  color: #fff !important;
  font-weight: 600;
}
.jigsaw-btn {
  font-weight: 600;
  text-transform: none;
  letter-spacing: normal;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.25);
}
</style>

// packages/mui/src/effects/JigsawPuzzle.tsx
import { useEffect, useLayoutEffect, useRef, type ReactNode } from "react"
import { Box, Button, Chip, Stack } from "@mui/material"
import { useMounted, useStore } from "@hc/react"
import { createJigsaw } from "@hc/core"

export interface JigsawPuzzleProps {
  children: ReactNode
  /** パズルの行数。@default 4 */
  rows?: number
  /** パズルの列数。@default 6 */
  cols?: number
  /** 効果のオン/オフ。オフのとき子要素は通常どおりレンダリングされる。@default true */
  active?: boolean
  /** ピースをシャッフルした状態でゲームを開始する。@default true */
  scattered?: boolean
  /** ユーザーがピースをドラッグできるようにする。@default true */
  draggable?: boolean
  /** フローティングの操作バー（Shuffle / Solve / 進捗）を表示する。@default true */
  controls?: boolean
  /** パズルの切り方を変える。@default 1 */
  seed?: number
  /** ピースが定位置にはまったときに合成したクリック音を鳴らす。@default true */
  sound?: boolean
  /** すべてのピースが定位置に固定されたときに一度だけ発火する。 */
  onSolved?: () => void
}

/**
 * 包んだ内容をジグソーパズルにする演出 (MUI)。
 * ピースの生成・ドラッグ・スナップ・効果音は @hc/core の createJigsaw が持ち、
 * ここは host 構造と操作バー (進捗・シャッフル・そろえる) とクリア表示を描くだけ。
 */
export function JigsawPuzzle({
  children,
  rows = 4,
  cols = 6,
  active = true,
  scattered = true,
  draggable = true,
  controls = true,
  seed = 1,
  sound = true,
  onSolved,
}: JigsawPuzzleProps) {
  const rootRef = useRef<HTMLDivElement>(null)
  const contentRef = useRef<HTMLDivElement>(null)
  const overlayRef = useRef<HTMLDivElement>(null)

  // onSolved は作りなおしの deps に入れず、最新版を ref 経由で呼ぶ。
  const onSolvedRef = useRef(onSolved)
  useLayoutEffect(() => {
    onSolvedRef.current = onSolved
  })

  const controller = useMounted(() => {
    const root = rootRef.current
    const content = contentRef.current
    const overlay = overlayRef.current
    if (!active || !root || !content || !overlay) return null
    return createJigsaw(
      { root, content, overlay },
      { rows, cols, seed, scattered, draggable, sound, onSolved: () => onSolvedRef.current?.() },
    )
    // sound は setSound で切り替えるので deps に入れない (パズルがばらけ直さないように)。
  }, [active, rows, cols, seed, scattered, draggable])
  useEffect(() => controller?.setSound(sound), [controller, sound])

  const state = useStore(controller)

  return (
    <div ref={rootRef}>
      <div ref={contentRef}>{children}</div>
      <div ref={overlayRef} />

      {/* クリア時のバナー */}
      {state?.solved && (
        <Box
          sx={{
            position: "absolute",
            inset: 0,
            display: "grid",
            placeItems: "center",
            pointerEvents: "none",
            zIndex: 10000,
          }}
        >
          <Box
            sx={{
              px: 3.5,
              py: 2,
              borderRadius: 4,
              bgcolor: "rgba(20,20,30,0.82)",
              color: "#fff",
              fontFamily: "system-ui, sans-serif",
              fontSize: 28,
              fontWeight: 800,
              letterSpacing: 1,
              boxShadow: "0 10px 30px rgba(0,0,0,0.45)",
            }}
          >
            🎉 クリア！
          </Box>
        </Box>
      )}

      {controller && state && controls && (
        <Stack
          direction="row"
          spacing={1}
          sx={{ position: "absolute", top: 12, right: 12, zIndex: 10001, alignItems: "center" }}
        >
          <Chip
            size="small"
            label={`${state.placed} / ${state.total}`}
            sx={{ bgcolor: "rgba(20,20,30,0.7)", color: "#fff", fontWeight: 600 }}
          />
          <Button variant="contained" onClick={controller.shuffle} sx={pill("#e8543f")}>
            🔀 シャッフル
          </Button>
          <Button variant="contained" onClick={controller.solve} sx={pill("#2d8f5a")}>
            🧩 そろえる
          </Button>
        </Stack>
      )}
    </div>
  )
}

/** 丸い色付きボタン (元のデザインの色をそのまま使う)。 */
function pill(bg: string) {
  return {
    borderRadius: 999,
    bgcolor: bg,
    color: "#fff",
    fontWeight: 600,
    textTransform: "none",
    boxShadow: "0 2px 8px rgba(0,0,0,0.25)",
    "&:hover": { bgcolor: bg, filter: "brightness(1.08)" },
  } as const
}

export default JigsawPuzzle
